---
apiVersion: v1
kind: Pod
metadata:
  name: trail-4
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-jdk17
      resources:
        requests:
          cpu: 500m
          memory: 256mi
        limits:
          cpu: 1000m
          memory: 1Gi    