---
apiVersion: v1
kind: ReplicationController
metadata:
  name: trail8-rsc
  labels:
    app: nginx
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources: 
            cpu: "500m"
            memory: "256Mi"
          args:
            - sleep
            - 1d  
