---
apiVersion: v1
kind: Service
metadata: 
  name: apache-svc
  labels:
    app: apache 
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
