---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail7-rs
  labels:
    name: trail7
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: liberica-openjdk-alpine:17-cds
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
